apiVersion: v1
kind: Service
metadata:
  name: zuulserver
  labels:
    app: zuulserver
spec:
  type: NodePort
  ports:
  - port: 5555
    nodePort: 30005
    protocol: TCP
  selector:
    app: zuulserver
